### ISSUE TITLE
Launch plan

### ISSUE THREAD

**Issue by cvan** [MozillaReality/puzzle-rain#88]
# Scheduled release time

Wed Oct 5, 2016 @ 11 AM PDT
# Outstanding issues (non-blockers)
1. [ ] #87: Investigate regular crashes in Chromium (@cvan filed toji/webvr.info#23 for @toji)
2. [ ] #13: Introduce Service Worker for network reliability, perf
3. [ ] #75: Fix mode switching, routes
4. [x] Test splash and fallback pages extensively across platforms + devices; push local branch of responsive layout style changes
# Deployment and testing plan
1. Deploy to [production](https://mozvr.com/puzzle-rain/):
   
   ``` bash
   npm run deploy
   ```
2. Test the blog post, splash page, normal mode, spectator mode, and fallback (when WebVR support is unavailable) in the following browsers:
   - [x] Windows desktop (most important because of VR support)
     - [x] **Chromium on Windows**
     - [x] **Firefox Nightly on Windows** (that it at least loads)
     - [x] Chrome (release) on Windows
     - [x] Firefox (release) on Windows
   - [x] Mac OS X / Linux desktop (experience unsupported)
     - [x] Chromium on Windows
     - [x] Firefox Nightly on Windows
     - [x] Chrome (release) on Windows
     - [x] Firefox (release) on Windows
   - [x] Mobile (experience unsupported)
     - [ ] [Chromium for Android](https://webvr.info/get-chrome/)
     - [x] Chrome for Android
     - [ ] Firefox for iOS
     - [ ] Firefox for Android
# Post-launch items
1. Tweet from [`@mozillavr`](https://twitter.com/mozillavr) with Vine looped video + link to blog post (#60 - @caseyyee)
   - [x] RTs from team and @arturitu (quotations optionals, but recommended) 
2. Post on A-Frame & WebVR Slack teams (or wait for people to share it and talk about it)
3. List on [Itch.io](https://itch.io/games/input-htc-vive/platform-web)

**Comment by cvan** [comment]
We launched… 2.5 years ago! 🎉

**Comment by fernandojsg** [comment]
wow, I think it's time to launch another hit isn't it? :P
